- debug:
    msg: "restoring from /backup/{{rollback_date}}/{{inventory_hostname}}.txt"

- shell: ls /tmp
- shell: "ls /tmp/{{ rollback_date }}"
- shell: "ls -la /tmp/{{ rollback_date }}"
- shell: "ls -la /tmp/{{ rollback_date }}/cisco"
- shell: "ls -la /tmp/{{ rollback_date }}/cisco/backup"
- shell: "ls -la /tmp/{{ rollback_date }}/cisco/backup/{{ rollback_date }}"
- shell: "ls -la /tmp/{{ rollback_date }}/cisco/backup/{{ rollback_date }}/cisco"

- name: restore the config
  cisco.ios.config:
    src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"

- name: print to terminal window
  debug:
    msg: "Restore is complete for device {{ inventory_hostname }} is set to {{ rollback_date }} timestamp"
